/**
 * Generated by ROHD - www.github.com/intel/rohd
 * Generation time: 2025-12-06 22:42:27.607 -08:00
 * ROHD Version: 0.6.6
 */

module Sum_1_W143 (
    input logic [7:0] amount_0,
    input logic [142:0] initialValue,
    input logic [142:0] minValue,
    input logic [142:0] maxValue,
    output logic overflowed,
    output logic underflowed,
    output logic equalsMax,
    output logic equalsMin,
    output logic [142:0] sum
);
  logic [144:0] _in0__swizzled_add_zeroPoint;
  logic [144:0] _in11__internalValue_subtract_upperSaturation_subtract_const_1_modulo_range_add_lowerSaturation;
  logic [144:0] _in2__internalValue_add__swizzled;
  logic _internalValue_add__swizzled_carry;
  logic _internalValue_subtract_upperSaturation_subtract_const_1_modulo_range_add_lowerSaturation_carry;
  logic _maxValueExt_add_zeroPoint_carry;
  logic _maxValueExt_subtract_minValueExt_add_const_1_carry;
  logic _minValueExt_add_zeroPoint_carry;
  logic _swizzled_add_zeroPoint_carry;
  logic [144:0] internalValue;
  logic [144:0] internalValueOverZeroPoint;
  logic [144:0] internalValue_0;
  logic [144:0] internalValue_1;
  logic [144:0] internalValue_2;
  logic [144:0] internalValue_3;
  logic [144:0] lowerSaturation;
  logic [144:0] maxValueExt;
  logic [144:0] minValueExt;
  logic [144:0] preAdjustmentValue;
  logic [144:0] range;
  logic [144:0] upperSaturation;
  logic [144:0] zeroPoint;
  assign zeroPoint = 145'h7fffffffffffffffffffffffffffffffffff;
  //  combinational_ssa
  always_comb begin
    internalValue_3 = _in0__swizzled_add_zeroPoint;
    internalValue_2 = _in2__internalValue_add__swizzled;
    overflowed = (internalValue_2 > upperSaturation);
    underflowed = (internalValue_2 < lowerSaturation);
    preAdjustmentValue = internalValue_2;
    if (overflowed) begin
      internalValue_0 = _in11__internalValue_subtract_upperSaturation_subtract_const_1_modulo_range_add_lowerSaturation;
      internalValue = internalValue_0;
      internalValue_1 = 145'h0;
    end else if (underflowed) begin
      internalValue_1 = (upperSaturation - (((lowerSaturation - internalValue_2) - 145'h1) % range));
      internalValue = internalValue_1;
      internalValue_0 = 145'h0;
    end else begin
      internalValue   = internalValue_2;
      internalValue_0 = 145'h0;
      internalValue_1 = 145'h0;
    end

  end

  assign {_swizzled_add_zeroPoint_carry, _in0__swizzled_add_zeroPoint} = ({2'h0,  /* 144:143 */
      initialValue  /* 142:  0 */
      }) + zeroPoint;
  assign {_maxValueExt_add_zeroPoint_carry, upperSaturation} = maxValueExt + zeroPoint;
  assign {_internalValue_subtract_upperSaturation_subtract_const_1_modulo_range_add_lowerSaturation_carry, _in11__internalValue_subtract_upperSaturation_subtract_const_1_modulo_range_add_lowerSaturation} = (((internalValue_2 - upperSaturation) - 145'h1) % range) + lowerSaturation;
  assign {_maxValueExt_subtract_minValueExt_add_const_1_carry, range} = (maxValueExt - minValueExt) + 145'h1;
  assign maxValueExt = {
    2'h0,  /* 144:143 */
    maxValue  /* 142:  0 */
  };  // swizzle_0
  assign {_minValueExt_add_zeroPoint_carry, lowerSaturation} = minValueExt + zeroPoint;
  assign minValueExt = {
    2'h0,  /* 144:143 */
    minValue  /* 142:  0 */
  };  // swizzle_1
  assign equalsMin = internalValue == lowerSaturation;  // equals
  assign internalValueOverZeroPoint = internalValue - zeroPoint;  // subtract_5
  assign sum = internalValueOverZeroPoint[142:0];  // bussubset
  assign equalsMax = internalValue == upperSaturation;  // equals_0
  assign {_internalValue_add__swizzled_carry, _in2__internalValue_add__swizzled} = internalValue_3 + ({
137'h0, /* 144:8 */
      amount_0  /*   7:0 */
      });
endmodule : Sum_1_W143

////////////////////

module Count_W141 (
    input  logic [140:0] bus,
    output logic [  7:0] countOne
);
  logic _const_0_add__swizzled_carry;
  logic _count_0_add__swizzled_carry;
  logic _count_100_add__swizzled_carry;
  logic _count_101_add__swizzled_carry;
  logic _count_102_add__swizzled_carry;
  logic _count_103_add__swizzled_carry;
  logic _count_104_add__swizzled_carry;
  logic _count_105_add__swizzled_carry;
  logic _count_106_add__swizzled_carry;
  logic _count_107_add__swizzled_carry;
  logic _count_108_add__swizzled_carry;
  logic _count_109_add__swizzled_carry;
  logic _count_10_add__swizzled_carry;
  logic _count_110_add__swizzled_carry;
  logic _count_111_add__swizzled_carry;
  logic _count_112_add__swizzled_carry;
  logic _count_113_add__swizzled_carry;
  logic _count_114_add__swizzled_carry;
  logic _count_115_add__swizzled_carry;
  logic _count_116_add__swizzled_carry;
  logic _count_117_add__swizzled_carry;
  logic _count_118_add__swizzled_carry;
  logic _count_119_add__swizzled_carry;
  logic _count_11_add__swizzled_carry;
  logic _count_120_add__swizzled_carry;
  logic _count_121_add__swizzled_carry;
  logic _count_122_add__swizzled_carry;
  logic _count_123_add__swizzled_carry;
  logic _count_124_add__swizzled_carry;
  logic _count_125_add__swizzled_carry;
  logic _count_126_add__swizzled_carry;
  logic _count_127_add__swizzled_carry;
  logic _count_128_add__swizzled_carry;
  logic _count_129_add__swizzled_carry;
  logic _count_12_add__swizzled_carry;
  logic _count_130_add__swizzled_carry;
  logic _count_131_add__swizzled_carry;
  logic _count_132_add__swizzled_carry;
  logic _count_133_add__swizzled_carry;
  logic _count_134_add__swizzled_carry;
  logic _count_135_add__swizzled_carry;
  logic _count_136_add__swizzled_carry;
  logic _count_137_add__swizzled_carry;
  logic _count_138_add__swizzled_carry;
  logic _count_139_add__swizzled_carry;
  logic _count_13_add__swizzled_carry;
  logic _count_14_add__swizzled_carry;
  logic _count_15_add__swizzled_carry;
  logic _count_16_add__swizzled_carry;
  logic _count_17_add__swizzled_carry;
  logic _count_18_add__swizzled_carry;
  logic _count_19_add__swizzled_carry;
  logic _count_1_add__swizzled_carry;
  logic _count_20_add__swizzled_carry;
  logic _count_21_add__swizzled_carry;
  logic _count_22_add__swizzled_carry;
  logic _count_23_add__swizzled_carry;
  logic _count_24_add__swizzled_carry;
  logic _count_25_add__swizzled_carry;
  logic _count_26_add__swizzled_carry;
  logic _count_27_add__swizzled_carry;
  logic _count_28_add__swizzled_carry;
  logic _count_29_add__swizzled_carry;
  logic _count_2_add__swizzled_carry;
  logic _count_30_add__swizzled_carry;
  logic _count_31_add__swizzled_carry;
  logic _count_32_add__swizzled_carry;
  logic _count_33_add__swizzled_carry;
  logic _count_34_add__swizzled_carry;
  logic _count_35_add__swizzled_carry;
  logic _count_36_add__swizzled_carry;
  logic _count_37_add__swizzled_carry;
  logic _count_38_add__swizzled_carry;
  logic _count_39_add__swizzled_carry;
  logic _count_3_add__swizzled_carry;
  logic _count_40_add__swizzled_carry;
  logic _count_41_add__swizzled_carry;
  logic _count_42_add__swizzled_carry;
  logic _count_43_add__swizzled_carry;
  logic _count_44_add__swizzled_carry;
  logic _count_45_add__swizzled_carry;
  logic _count_46_add__swizzled_carry;
  logic _count_47_add__swizzled_carry;
  logic _count_48_add__swizzled_carry;
  logic _count_49_add__swizzled_carry;
  logic _count_4_add__swizzled_carry;
  logic _count_50_add__swizzled_carry;
  logic _count_51_add__swizzled_carry;
  logic _count_52_add__swizzled_carry;
  logic _count_53_add__swizzled_carry;
  logic _count_54_add__swizzled_carry;
  logic _count_55_add__swizzled_carry;
  logic _count_56_add__swizzled_carry;
  logic _count_57_add__swizzled_carry;
  logic _count_58_add__swizzled_carry;
  logic _count_59_add__swizzled_carry;
  logic _count_5_add__swizzled_carry;
  logic _count_60_add__swizzled_carry;
  logic _count_61_add__swizzled_carry;
  logic _count_62_add__swizzled_carry;
  logic _count_63_add__swizzled_carry;
  logic _count_64_add__swizzled_carry;
  logic _count_65_add__swizzled_carry;
  logic _count_66_add__swizzled_carry;
  logic _count_67_add__swizzled_carry;
  logic _count_68_add__swizzled_carry;
  logic _count_69_add__swizzled_carry;
  logic _count_6_add__swizzled_carry;
  logic _count_70_add__swizzled_carry;
  logic _count_71_add__swizzled_carry;
  logic _count_72_add__swizzled_carry;
  logic _count_73_add__swizzled_carry;
  logic _count_74_add__swizzled_carry;
  logic _count_75_add__swizzled_carry;
  logic _count_76_add__swizzled_carry;
  logic _count_77_add__swizzled_carry;
  logic _count_78_add__swizzled_carry;
  logic _count_79_add__swizzled_carry;
  logic _count_7_add__swizzled_carry;
  logic _count_80_add__swizzled_carry;
  logic _count_81_add__swizzled_carry;
  logic _count_82_add__swizzled_carry;
  logic _count_83_add__swizzled_carry;
  logic _count_84_add__swizzled_carry;
  logic _count_85_add__swizzled_carry;
  logic _count_86_add__swizzled_carry;
  logic _count_87_add__swizzled_carry;
  logic _count_88_add__swizzled_carry;
  logic _count_89_add__swizzled_carry;
  logic _count_8_add__swizzled_carry;
  logic _count_90_add__swizzled_carry;
  logic _count_91_add__swizzled_carry;
  logic _count_92_add__swizzled_carry;
  logic _count_93_add__swizzled_carry;
  logic _count_94_add__swizzled_carry;
  logic _count_95_add__swizzled_carry;
  logic _count_96_add__swizzled_carry;
  logic _count_97_add__swizzled_carry;
  logic _count_98_add__swizzled_carry;
  logic _count_99_add__swizzled_carry;
  logic _count_9_add__swizzled_carry;
  logic [7:0] count_0;
  logic [7:0] count_1;
  logic [7:0] count_10;
  logic [7:0] count_100;
  logic [7:0] count_101;
  logic [7:0] count_102;
  logic [7:0] count_103;
  logic [7:0] count_104;
  logic [7:0] count_105;
  logic [7:0] count_106;
  logic [7:0] count_107;
  logic [7:0] count_108;
  logic [7:0] count_109;
  logic [7:0] count_11;
  logic [7:0] count_110;
  logic [7:0] count_111;
  logic [7:0] count_112;
  logic [7:0] count_113;
  logic [7:0] count_114;
  logic [7:0] count_115;
  logic [7:0] count_116;
  logic [7:0] count_117;
  logic [7:0] count_118;
  logic [7:0] count_119;
  logic [7:0] count_12;
  logic [7:0] count_120;
  logic [7:0] count_121;
  logic [7:0] count_122;
  logic [7:0] count_123;
  logic [7:0] count_124;
  logic [7:0] count_125;
  logic [7:0] count_126;
  logic [7:0] count_127;
  logic [7:0] count_128;
  logic [7:0] count_129;
  logic [7:0] count_13;
  logic [7:0] count_130;
  logic [7:0] count_131;
  logic [7:0] count_132;
  logic [7:0] count_133;
  logic [7:0] count_134;
  logic [7:0] count_135;
  logic [7:0] count_136;
  logic [7:0] count_137;
  logic [7:0] count_138;
  logic [7:0] count_139;
  logic [7:0] count_14;
  logic [7:0] count_140;
  logic [7:0] count_15;
  logic [7:0] count_16;
  logic [7:0] count_17;
  logic [7:0] count_18;
  logic [7:0] count_19;
  logic [7:0] count_2;
  logic [7:0] count_20;
  logic [7:0] count_21;
  logic [7:0] count_22;
  logic [7:0] count_23;
  logic [7:0] count_24;
  logic [7:0] count_25;
  logic [7:0] count_26;
  logic [7:0] count_27;
  logic [7:0] count_28;
  logic [7:0] count_29;
  logic [7:0] count_3;
  logic [7:0] count_30;
  logic [7:0] count_31;
  logic [7:0] count_32;
  logic [7:0] count_33;
  logic [7:0] count_34;
  logic [7:0] count_35;
  logic [7:0] count_36;
  logic [7:0] count_37;
  logic [7:0] count_38;
  logic [7:0] count_39;
  logic [7:0] count_4;
  logic [7:0] count_40;
  logic [7:0] count_41;
  logic [7:0] count_42;
  logic [7:0] count_43;
  logic [7:0] count_44;
  logic [7:0] count_45;
  logic [7:0] count_46;
  logic [7:0] count_47;
  logic [7:0] count_48;
  logic [7:0] count_49;
  logic [7:0] count_5;
  logic [7:0] count_50;
  logic [7:0] count_51;
  logic [7:0] count_52;
  logic [7:0] count_53;
  logic [7:0] count_54;
  logic [7:0] count_55;
  logic [7:0] count_56;
  logic [7:0] count_57;
  logic [7:0] count_58;
  logic [7:0] count_59;
  logic [7:0] count_6;
  logic [7:0] count_60;
  logic [7:0] count_61;
  logic [7:0] count_62;
  logic [7:0] count_63;
  logic [7:0] count_64;
  logic [7:0] count_65;
  logic [7:0] count_66;
  logic [7:0] count_67;
  logic [7:0] count_68;
  logic [7:0] count_69;
  logic [7:0] count_7;
  logic [7:0] count_70;
  logic [7:0] count_71;
  logic [7:0] count_72;
  logic [7:0] count_73;
  logic [7:0] count_74;
  logic [7:0] count_75;
  logic [7:0] count_76;
  logic [7:0] count_77;
  logic [7:0] count_78;
  logic [7:0] count_79;
  logic [7:0] count_8;
  logic [7:0] count_80;
  logic [7:0] count_81;
  logic [7:0] count_82;
  logic [7:0] count_83;
  logic [7:0] count_84;
  logic [7:0] count_85;
  logic [7:0] count_86;
  logic [7:0] count_87;
  logic [7:0] count_88;
  logic [7:0] count_89;
  logic [7:0] count_9;
  logic [7:0] count_90;
  logic [7:0] count_91;
  logic [7:0] count_92;
  logic [7:0] count_93;
  logic [7:0] count_94;
  logic [7:0] count_95;
  logic [7:0] count_96;
  logic [7:0] count_97;
  logic [7:0] count_98;
  logic [7:0] count_99;
  assign countOne = count_140;
  assign {_count_139_add__swizzled_carry, count_140} = count_139 + ({7'h0,  /* 7:1 */
      (bus[140])  /*   0 */
      });
  assign {_count_138_add__swizzled_carry, count_139} = count_138 + ({7'h0,  /* 7:1 */
      (bus[139])  /*   0 */
      });
  assign {_count_137_add__swizzled_carry, count_138} = count_137 + ({7'h0,  /* 7:1 */
      (bus[138])  /*   0 */
      });
  assign {_count_136_add__swizzled_carry, count_137} = count_136 + ({7'h0,  /* 7:1 */
      (bus[137])  /*   0 */
      });
  assign {_count_135_add__swizzled_carry, count_136} = count_135 + ({7'h0,  /* 7:1 */
      (bus[136])  /*   0 */
      });
  assign {_count_134_add__swizzled_carry, count_135} = count_134 + ({7'h0,  /* 7:1 */
      (bus[135])  /*   0 */
      });
  assign {_count_133_add__swizzled_carry, count_134} = count_133 + ({7'h0,  /* 7:1 */
      (bus[134])  /*   0 */
      });
  assign {_count_132_add__swizzled_carry, count_133} = count_132 + ({7'h0,  /* 7:1 */
      (bus[133])  /*   0 */
      });
  assign {_count_131_add__swizzled_carry, count_132} = count_131 + ({7'h0,  /* 7:1 */
      (bus[132])  /*   0 */
      });
  assign {_count_130_add__swizzled_carry, count_131} = count_130 + ({7'h0,  /* 7:1 */
      (bus[131])  /*   0 */
      });
  assign {_count_129_add__swizzled_carry, count_130} = count_129 + ({7'h0,  /* 7:1 */
      (bus[130])  /*   0 */
      });
  assign {_count_128_add__swizzled_carry, count_129} = count_128 + ({7'h0,  /* 7:1 */
      (bus[129])  /*   0 */
      });
  assign {_count_127_add__swizzled_carry, count_128} = count_127 + ({7'h0,  /* 7:1 */
      (bus[128])  /*   0 */
      });
  assign {_count_126_add__swizzled_carry, count_127} = count_126 + ({7'h0,  /* 7:1 */
      (bus[127])  /*   0 */
      });
  assign {_count_125_add__swizzled_carry, count_126} = count_125 + ({7'h0,  /* 7:1 */
      (bus[126])  /*   0 */
      });
  assign {_count_124_add__swizzled_carry, count_125} = count_124 + ({7'h0,  /* 7:1 */
      (bus[125])  /*   0 */
      });
  assign {_count_123_add__swizzled_carry, count_124} = count_123 + ({7'h0,  /* 7:1 */
      (bus[124])  /*   0 */
      });
  assign {_count_122_add__swizzled_carry, count_123} = count_122 + ({7'h0,  /* 7:1 */
      (bus[123])  /*   0 */
      });
  assign {_count_121_add__swizzled_carry, count_122} = count_121 + ({7'h0,  /* 7:1 */
      (bus[122])  /*   0 */
      });
  assign {_count_120_add__swizzled_carry, count_121} = count_120 + ({7'h0,  /* 7:1 */
      (bus[121])  /*   0 */
      });
  assign {_count_119_add__swizzled_carry, count_120} = count_119 + ({7'h0,  /* 7:1 */
      (bus[120])  /*   0 */
      });
  assign {_count_118_add__swizzled_carry, count_119} = count_118 + ({7'h0,  /* 7:1 */
      (bus[119])  /*   0 */
      });
  assign {_count_117_add__swizzled_carry, count_118} = count_117 + ({7'h0,  /* 7:1 */
      (bus[118])  /*   0 */
      });
  assign {_count_116_add__swizzled_carry, count_117} = count_116 + ({7'h0,  /* 7:1 */
      (bus[117])  /*   0 */
      });
  assign {_count_115_add__swizzled_carry, count_116} = count_115 + ({7'h0,  /* 7:1 */
      (bus[116])  /*   0 */
      });
  assign {_count_114_add__swizzled_carry, count_115} = count_114 + ({7'h0,  /* 7:1 */
      (bus[115])  /*   0 */
      });
  assign {_count_113_add__swizzled_carry, count_114} = count_113 + ({7'h0,  /* 7:1 */
      (bus[114])  /*   0 */
      });
  assign {_count_112_add__swizzled_carry, count_113} = count_112 + ({7'h0,  /* 7:1 */
      (bus[113])  /*   0 */
      });
  assign {_count_111_add__swizzled_carry, count_112} = count_111 + ({7'h0,  /* 7:1 */
      (bus[112])  /*   0 */
      });
  assign {_count_110_add__swizzled_carry, count_111} = count_110 + ({7'h0,  /* 7:1 */
      (bus[111])  /*   0 */
      });
  assign {_count_109_add__swizzled_carry, count_110} = count_109 + ({7'h0,  /* 7:1 */
      (bus[110])  /*   0 */
      });
  assign {_count_108_add__swizzled_carry, count_109} = count_108 + ({7'h0,  /* 7:1 */
      (bus[109])  /*   0 */
      });
  assign {_count_107_add__swizzled_carry, count_108} = count_107 + ({7'h0,  /* 7:1 */
      (bus[108])  /*   0 */
      });
  assign {_count_106_add__swizzled_carry, count_107} = count_106 + ({7'h0,  /* 7:1 */
      (bus[107])  /*   0 */
      });
  assign {_count_105_add__swizzled_carry, count_106} = count_105 + ({7'h0,  /* 7:1 */
      (bus[106])  /*   0 */
      });
  assign {_count_104_add__swizzled_carry, count_105} = count_104 + ({7'h0,  /* 7:1 */
      (bus[105])  /*   0 */
      });
  assign {_count_103_add__swizzled_carry, count_104} = count_103 + ({7'h0,  /* 7:1 */
      (bus[104])  /*   0 */
      });
  assign {_count_102_add__swizzled_carry, count_103} = count_102 + ({7'h0,  /* 7:1 */
      (bus[103])  /*   0 */
      });
  assign {_count_101_add__swizzled_carry, count_102} = count_101 + ({7'h0,  /* 7:1 */
      (bus[102])  /*   0 */
      });
  assign {_count_100_add__swizzled_carry, count_101} = count_100 + ({7'h0,  /* 7:1 */
      (bus[101])  /*   0 */
      });
  assign {_count_99_add__swizzled_carry, count_100} = count_99 + ({7'h0,  /* 7:1 */
      (bus[100])  /*   0 */
      });
  assign {_count_98_add__swizzled_carry, count_99} = count_98 + ({7'h0,  /* 7:1 */
      (bus[99])  /*   0 */
      });
  assign {_count_97_add__swizzled_carry, count_98} = count_97 + ({7'h0,  /* 7:1 */
      (bus[98])  /*   0 */
      });
  assign {_count_96_add__swizzled_carry, count_97} = count_96 + ({7'h0,  /* 7:1 */
      (bus[97])  /*   0 */
      });
  assign {_count_95_add__swizzled_carry, count_96} = count_95 + ({7'h0,  /* 7:1 */
      (bus[96])  /*   0 */
      });
  assign {_count_94_add__swizzled_carry, count_95} = count_94 + ({7'h0,  /* 7:1 */
      (bus[95])  /*   0 */
      });
  assign {_count_93_add__swizzled_carry, count_94} = count_93 + ({7'h0,  /* 7:1 */
      (bus[94])  /*   0 */
      });
  assign {_count_92_add__swizzled_carry, count_93} = count_92 + ({7'h0,  /* 7:1 */
      (bus[93])  /*   0 */
      });
  assign {_count_91_add__swizzled_carry, count_92} = count_91 + ({7'h0,  /* 7:1 */
      (bus[92])  /*   0 */
      });
  assign {_count_90_add__swizzled_carry, count_91} = count_90 + ({7'h0,  /* 7:1 */
      (bus[91])  /*   0 */
      });
  assign {_count_89_add__swizzled_carry, count_90} = count_89 + ({7'h0,  /* 7:1 */
      (bus[90])  /*   0 */
      });
  assign {_count_88_add__swizzled_carry, count_89} = count_88 + ({7'h0,  /* 7:1 */
      (bus[89])  /*   0 */
      });
  assign {_count_87_add__swizzled_carry, count_88} = count_87 + ({7'h0,  /* 7:1 */
      (bus[88])  /*   0 */
      });
  assign {_count_86_add__swizzled_carry, count_87} = count_86 + ({7'h0,  /* 7:1 */
      (bus[87])  /*   0 */
      });
  assign {_count_85_add__swizzled_carry, count_86} = count_85 + ({7'h0,  /* 7:1 */
      (bus[86])  /*   0 */
      });
  assign {_count_84_add__swizzled_carry, count_85} = count_84 + ({7'h0,  /* 7:1 */
      (bus[85])  /*   0 */
      });
  assign {_count_83_add__swizzled_carry, count_84} = count_83 + ({7'h0,  /* 7:1 */
      (bus[84])  /*   0 */
      });
  assign {_count_82_add__swizzled_carry, count_83} = count_82 + ({7'h0,  /* 7:1 */
      (bus[83])  /*   0 */
      });
  assign {_count_81_add__swizzled_carry, count_82} = count_81 + ({7'h0,  /* 7:1 */
      (bus[82])  /*   0 */
      });
  assign {_count_80_add__swizzled_carry, count_81} = count_80 + ({7'h0,  /* 7:1 */
      (bus[81])  /*   0 */
      });
  assign {_count_79_add__swizzled_carry, count_80} = count_79 + ({7'h0,  /* 7:1 */
      (bus[80])  /*   0 */
      });
  assign {_count_78_add__swizzled_carry, count_79} = count_78 + ({7'h0,  /* 7:1 */
      (bus[79])  /*   0 */
      });
  assign {_count_77_add__swizzled_carry, count_78} = count_77 + ({7'h0,  /* 7:1 */
      (bus[78])  /*   0 */
      });
  assign {_count_76_add__swizzled_carry, count_77} = count_76 + ({7'h0,  /* 7:1 */
      (bus[77])  /*   0 */
      });
  assign {_count_75_add__swizzled_carry, count_76} = count_75 + ({7'h0,  /* 7:1 */
      (bus[76])  /*   0 */
      });
  assign {_count_74_add__swizzled_carry, count_75} = count_74 + ({7'h0,  /* 7:1 */
      (bus[75])  /*   0 */
      });
  assign {_count_73_add__swizzled_carry, count_74} = count_73 + ({7'h0,  /* 7:1 */
      (bus[74])  /*   0 */
      });
  assign {_count_72_add__swizzled_carry, count_73} = count_72 + ({7'h0,  /* 7:1 */
      (bus[73])  /*   0 */
      });
  assign {_count_71_add__swizzled_carry, count_72} = count_71 + ({7'h0,  /* 7:1 */
      (bus[72])  /*   0 */
      });
  assign {_count_70_add__swizzled_carry, count_71} = count_70 + ({7'h0,  /* 7:1 */
      (bus[71])  /*   0 */
      });
  assign {_count_69_add__swizzled_carry, count_70} = count_69 + ({7'h0,  /* 7:1 */
      (bus[70])  /*   0 */
      });
  assign {_count_68_add__swizzled_carry, count_69} = count_68 + ({7'h0,  /* 7:1 */
      (bus[69])  /*   0 */
      });
  assign {_count_67_add__swizzled_carry, count_68} = count_67 + ({7'h0,  /* 7:1 */
      (bus[68])  /*   0 */
      });
  assign {_count_66_add__swizzled_carry, count_67} = count_66 + ({7'h0,  /* 7:1 */
      (bus[67])  /*   0 */
      });
  assign {_count_65_add__swizzled_carry, count_66} = count_65 + ({7'h0,  /* 7:1 */
      (bus[66])  /*   0 */
      });
  assign {_count_64_add__swizzled_carry, count_65} = count_64 + ({7'h0,  /* 7:1 */
      (bus[65])  /*   0 */
      });
  assign {_count_63_add__swizzled_carry, count_64} = count_63 + ({7'h0,  /* 7:1 */
      (bus[64])  /*   0 */
      });
  assign {_count_62_add__swizzled_carry, count_63} = count_62 + ({7'h0,  /* 7:1 */
      (bus[63])  /*   0 */
      });
  assign {_count_61_add__swizzled_carry, count_62} = count_61 + ({7'h0,  /* 7:1 */
      (bus[62])  /*   0 */
      });
  assign {_count_60_add__swizzled_carry, count_61} = count_60 + ({7'h0,  /* 7:1 */
      (bus[61])  /*   0 */
      });
  assign {_count_59_add__swizzled_carry, count_60} = count_59 + ({7'h0,  /* 7:1 */
      (bus[60])  /*   0 */
      });
  assign {_count_58_add__swizzled_carry, count_59} = count_58 + ({7'h0,  /* 7:1 */
      (bus[59])  /*   0 */
      });
  assign {_count_57_add__swizzled_carry, count_58} = count_57 + ({7'h0,  /* 7:1 */
      (bus[58])  /*   0 */
      });
  assign {_count_56_add__swizzled_carry, count_57} = count_56 + ({7'h0,  /* 7:1 */
      (bus[57])  /*   0 */
      });
  assign {_count_55_add__swizzled_carry, count_56} = count_55 + ({7'h0,  /* 7:1 */
      (bus[56])  /*   0 */
      });
  assign {_count_54_add__swizzled_carry, count_55} = count_54 + ({7'h0,  /* 7:1 */
      (bus[55])  /*   0 */
      });
  assign {_count_53_add__swizzled_carry, count_54} = count_53 + ({7'h0,  /* 7:1 */
      (bus[54])  /*   0 */
      });
  assign {_count_52_add__swizzled_carry, count_53} = count_52 + ({7'h0,  /* 7:1 */
      (bus[53])  /*   0 */
      });
  assign {_count_51_add__swizzled_carry, count_52} = count_51 + ({7'h0,  /* 7:1 */
      (bus[52])  /*   0 */
      });
  assign {_count_50_add__swizzled_carry, count_51} = count_50 + ({7'h0,  /* 7:1 */
      (bus[51])  /*   0 */
      });
  assign {_count_49_add__swizzled_carry, count_50} = count_49 + ({7'h0,  /* 7:1 */
      (bus[50])  /*   0 */
      });
  assign {_count_48_add__swizzled_carry, count_49} = count_48 + ({7'h0,  /* 7:1 */
      (bus[49])  /*   0 */
      });
  assign {_count_47_add__swizzled_carry, count_48} = count_47 + ({7'h0,  /* 7:1 */
      (bus[48])  /*   0 */
      });
  assign {_count_46_add__swizzled_carry, count_47} = count_46 + ({7'h0,  /* 7:1 */
      (bus[47])  /*   0 */
      });
  assign {_count_45_add__swizzled_carry, count_46} = count_45 + ({7'h0,  /* 7:1 */
      (bus[46])  /*   0 */
      });
  assign {_count_44_add__swizzled_carry, count_45} = count_44 + ({7'h0,  /* 7:1 */
      (bus[45])  /*   0 */
      });
  assign {_count_43_add__swizzled_carry, count_44} = count_43 + ({7'h0,  /* 7:1 */
      (bus[44])  /*   0 */
      });
  assign {_count_42_add__swizzled_carry, count_43} = count_42 + ({7'h0,  /* 7:1 */
      (bus[43])  /*   0 */
      });
  assign {_count_41_add__swizzled_carry, count_42} = count_41 + ({7'h0,  /* 7:1 */
      (bus[42])  /*   0 */
      });
  assign {_count_40_add__swizzled_carry, count_41} = count_40 + ({7'h0,  /* 7:1 */
      (bus[41])  /*   0 */
      });
  assign {_count_39_add__swizzled_carry, count_40} = count_39 + ({7'h0,  /* 7:1 */
      (bus[40])  /*   0 */
      });
  assign {_count_38_add__swizzled_carry, count_39} = count_38 + ({7'h0,  /* 7:1 */
      (bus[39])  /*   0 */
      });
  assign {_count_37_add__swizzled_carry, count_38} = count_37 + ({7'h0,  /* 7:1 */
      (bus[38])  /*   0 */
      });
  assign {_count_36_add__swizzled_carry, count_37} = count_36 + ({7'h0,  /* 7:1 */
      (bus[37])  /*   0 */
      });
  assign {_count_35_add__swizzled_carry, count_36} = count_35 + ({7'h0,  /* 7:1 */
      (bus[36])  /*   0 */
      });
  assign {_count_34_add__swizzled_carry, count_35} = count_34 + ({7'h0,  /* 7:1 */
      (bus[35])  /*   0 */
      });
  assign {_count_33_add__swizzled_carry, count_34} = count_33 + ({7'h0,  /* 7:1 */
      (bus[34])  /*   0 */
      });
  assign {_count_32_add__swizzled_carry, count_33} = count_32 + ({7'h0,  /* 7:1 */
      (bus[33])  /*   0 */
      });
  assign {_count_31_add__swizzled_carry, count_32} = count_31 + ({7'h0,  /* 7:1 */
      (bus[32])  /*   0 */
      });
  assign {_count_30_add__swizzled_carry, count_31} = count_30 + ({7'h0,  /* 7:1 */
      (bus[31])  /*   0 */
      });
  assign {_count_29_add__swizzled_carry, count_30} = count_29 + ({7'h0,  /* 7:1 */
      (bus[30])  /*   0 */
      });
  assign {_count_28_add__swizzled_carry, count_29} = count_28 + ({7'h0,  /* 7:1 */
      (bus[29])  /*   0 */
      });
  assign {_count_27_add__swizzled_carry, count_28} = count_27 + ({7'h0,  /* 7:1 */
      (bus[28])  /*   0 */
      });
  assign {_count_26_add__swizzled_carry, count_27} = count_26 + ({7'h0,  /* 7:1 */
      (bus[27])  /*   0 */
      });
  assign {_count_25_add__swizzled_carry, count_26} = count_25 + ({7'h0,  /* 7:1 */
      (bus[26])  /*   0 */
      });
  assign {_count_24_add__swizzled_carry, count_25} = count_24 + ({7'h0,  /* 7:1 */
      (bus[25])  /*   0 */
      });
  assign {_count_23_add__swizzled_carry, count_24} = count_23 + ({7'h0,  /* 7:1 */
      (bus[24])  /*   0 */
      });
  assign {_count_22_add__swizzled_carry, count_23} = count_22 + ({7'h0,  /* 7:1 */
      (bus[23])  /*   0 */
      });
  assign {_count_21_add__swizzled_carry, count_22} = count_21 + ({7'h0,  /* 7:1 */
      (bus[22])  /*   0 */
      });
  assign {_count_20_add__swizzled_carry, count_21} = count_20 + ({7'h0,  /* 7:1 */
      (bus[21])  /*   0 */
      });
  assign {_count_19_add__swizzled_carry, count_20} = count_19 + ({7'h0,  /* 7:1 */
      (bus[20])  /*   0 */
      });
  assign {_count_18_add__swizzled_carry, count_19} = count_18 + ({7'h0,  /* 7:1 */
      (bus[19])  /*   0 */
      });
  assign {_count_17_add__swizzled_carry, count_18} = count_17 + ({7'h0,  /* 7:1 */
      (bus[18])  /*   0 */
      });
  assign {_count_16_add__swizzled_carry, count_17} = count_16 + ({7'h0,  /* 7:1 */
      (bus[17])  /*   0 */
      });
  assign {_count_15_add__swizzled_carry, count_16} = count_15 + ({7'h0,  /* 7:1 */
      (bus[16])  /*   0 */
      });
  assign {_count_14_add__swizzled_carry, count_15} = count_14 + ({7'h0,  /* 7:1 */
      (bus[15])  /*   0 */
      });
  assign {_count_13_add__swizzled_carry, count_14} = count_13 + ({7'h0,  /* 7:1 */
      (bus[14])  /*   0 */
      });
  assign {_count_12_add__swizzled_carry, count_13} = count_12 + ({7'h0,  /* 7:1 */
      (bus[13])  /*   0 */
      });
  assign {_count_11_add__swizzled_carry, count_12} = count_11 + ({7'h0,  /* 7:1 */
      (bus[12])  /*   0 */
      });
  assign {_count_10_add__swizzled_carry, count_11} = count_10 + ({7'h0,  /* 7:1 */
      (bus[11])  /*   0 */
      });
  assign {_count_9_add__swizzled_carry, count_10} = count_9 + ({7'h0,  /* 7:1 */
      (bus[10])  /*   0 */
      });
  assign {_count_8_add__swizzled_carry, count_9} = count_8 + ({7'h0,  /* 7:1 */
      (bus[9])  /*   0 */
      });
  assign {_count_7_add__swizzled_carry, count_8} = count_7 + ({7'h0,  /* 7:1 */
      (bus[8])  /*   0 */
      });
  assign {_count_6_add__swizzled_carry, count_7} = count_6 + ({7'h0,  /* 7:1 */
      (bus[7])  /*   0 */
      });
  assign {_count_5_add__swizzled_carry, count_6} = count_5 + ({7'h0,  /* 7:1 */
      (bus[6])  /*   0 */
      });
  assign {_count_4_add__swizzled_carry, count_5} = count_4 + ({7'h0,  /* 7:1 */
      (bus[5])  /*   0 */
      });
  assign {_count_3_add__swizzled_carry, count_4} = count_3 + ({7'h0,  /* 7:1 */
      (bus[4])  /*   0 */
      });
  assign {_count_2_add__swizzled_carry, count_3} = count_2 + ({7'h0,  /* 7:1 */
      (bus[3])  /*   0 */
      });
  assign {_count_1_add__swizzled_carry, count_2} = count_1 + ({7'h0,  /* 7:1 */
      (bus[2])  /*   0 */
      });
  assign {_count_0_add__swizzled_carry, count_1} = count_0 + ({7'h0,  /* 7:1 */
      (bus[1])  /*   0 */
      });
  assign {_const_0_add__swizzled_carry, count_0} = 8'h0 + ({7'h0,  /* 7:1 */
      (bus[0])  /*   0 */
      });
endmodule : Count_W141

////////////////////

module Counter_L1_ (
    input logic [7:0] amount_0,
    input logic clk,
    input logic reset,
    output logic overflowed,
    output logic underflowed,
    output logic equalsMax,
    output logic equalsMin,
    output logic [142:0] count
);
  logic [142:0] initialValue;
  logic [142:0] maxValue;
  logic [142:0] minValue;
  logic overflowed_0;
  logic [142:0] sum_0;
  logic underflowed_0;
  assign initialValue = 143'h0;
  assign minValue = 143'h0;
  assign maxValue = 143'h7fffffffffffffffffffffffffffffffffff;
  always_ff @(posedge clk)
    if (reset) overflowed <= 1'h0;
    else overflowed <= overflowed_0;  // flipflop
  Sum_1_W143 sum (
      .amount_0(amount_0),
      .initialValue((count)),
      .minValue((minValue)),
      .maxValue((maxValue)),
      .overflowed(overflowed_0),
      .underflowed(underflowed_0),
      .equalsMax(),
      .equalsMin(),
      .sum(sum_0)
  );
  always_ff @(posedge clk)
    if (reset) count <= initialValue;
    else count <= sum_0;  // flipflop_0
  assign equalsMin = count == minValue;  // equals
  assign equalsMax = count == maxValue;  // equals_0
  always_ff @(posedge clk)
    if (reset) underflowed <= 1'h0;
    else underflowed <= underflowed_0;  // flipflop_1
endmodule : Counter_L1_

////////////////////

module Day07p1 (
    input logic clk,
    input logic reset,
    input logic [140:0] splitterVector,
    output logic [142:0] totalSplittersHitCount
);
  logic [140:0] laserPresent;
  logic [140:0] splitterHit;
  logic [  7:0] splittersHitCountInRow;
  logic [142:0] totalSplittersHitCount_0;
  assign totalSplittersHitCount = totalSplittersHitCount_0;
  Counter_L1_ counter (
      .amount_0(splittersHitCountInRow),
      .clk(clk),
      .reset(reset),
      .overflowed(),
      .underflowed(),
      .equalsMax(),
      .equalsMin(),
      .count(totalSplittersHitCount_0)
  );
  Count_W141 count (
      .bus(splitterHit),
      .countOne(splittersHitCountInRow)
  );
  always_ff @(posedge clk)
    if (reset) laserPresent <= 141'h400000000000000000;
    else
      laserPresent <= ({
        ((~(splitterVector[140])) & ((|(splitterHit[139])) | (laserPresent[140]))),  /* 140 */
        ((~(splitterVector[139])) & ((|({(splitterHit[138]),  /* 1 */
        (splitterHit[140])  /* 0 */
        })) | (laserPresent[139]))),  /* 139 */
        ((~(splitterVector[138])) & ((|({(splitterHit[137]),  /* 1 */
        (splitterHit[139])  /* 0 */
        })) | (laserPresent[138]))),  /* 138 */
        ((~(splitterVector[137])) & ((|({(splitterHit[136]),  /* 1 */
        (splitterHit[138])  /* 0 */
        })) | (laserPresent[137]))),  /* 137 */
        ((~(splitterVector[136])) & ((|({(splitterHit[135]),  /* 1 */
        (splitterHit[137])  /* 0 */
        })) | (laserPresent[136]))),  /* 136 */
        ((~(splitterVector[135])) & ((|({(splitterHit[134]),  /* 1 */
        (splitterHit[136])  /* 0 */
        })) | (laserPresent[135]))),  /* 135 */
        ((~(splitterVector[134])) & ((|({(splitterHit[133]),  /* 1 */
        (splitterHit[135])  /* 0 */
        })) | (laserPresent[134]))),  /* 134 */
        ((~(splitterVector[133])) & ((|({(splitterHit[132]),  /* 1 */
        (splitterHit[134])  /* 0 */
        })) | (laserPresent[133]))),  /* 133 */
        ((~(splitterVector[132])) & ((|({(splitterHit[131]),  /* 1 */
        (splitterHit[133])  /* 0 */
        })) | (laserPresent[132]))),  /* 132 */
        ((~(splitterVector[131])) & ((|({(splitterHit[130]),  /* 1 */
        (splitterHit[132])  /* 0 */
        })) | (laserPresent[131]))),  /* 131 */
        ((~(splitterVector[130])) & ((|({(splitterHit[129]),  /* 1 */
        (splitterHit[131])  /* 0 */
        })) | (laserPresent[130]))),  /* 130 */
        ((~(splitterVector[129])) & ((|({(splitterHit[128]),  /* 1 */
        (splitterHit[130])  /* 0 */
        })) | (laserPresent[129]))),  /* 129 */
        ((~(splitterVector[128])) & ((|({(splitterHit[127]),  /* 1 */
        (splitterHit[129])  /* 0 */
        })) | (laserPresent[128]))),  /* 128 */
        ((~(splitterVector[127])) & ((|({(splitterHit[126]),  /* 1 */
        (splitterHit[128])  /* 0 */
        })) | (laserPresent[127]))),  /* 127 */
        ((~(splitterVector[126])) & ((|({(splitterHit[125]),  /* 1 */
        (splitterHit[127])  /* 0 */
        })) | (laserPresent[126]))),  /* 126 */
        ((~(splitterVector[125])) & ((|({(splitterHit[124]),  /* 1 */
        (splitterHit[126])  /* 0 */
        })) | (laserPresent[125]))),  /* 125 */
        ((~(splitterVector[124])) & ((|({(splitterHit[123]),  /* 1 */
        (splitterHit[125])  /* 0 */
        })) | (laserPresent[124]))),  /* 124 */
        ((~(splitterVector[123])) & ((|({(splitterHit[122]),  /* 1 */
        (splitterHit[124])  /* 0 */
        })) | (laserPresent[123]))),  /* 123 */
        ((~(splitterVector[122])) & ((|({(splitterHit[121]),  /* 1 */
        (splitterHit[123])  /* 0 */
        })) | (laserPresent[122]))),  /* 122 */
        ((~(splitterVector[121])) & ((|({(splitterHit[120]),  /* 1 */
        (splitterHit[122])  /* 0 */
        })) | (laserPresent[121]))),  /* 121 */
        ((~(splitterVector[120])) & ((|({(splitterHit[119]),  /* 1 */
        (splitterHit[121])  /* 0 */
        })) | (laserPresent[120]))),  /* 120 */
        ((~(splitterVector[119])) & ((|({(splitterHit[118]),  /* 1 */
        (splitterHit[120])  /* 0 */
        })) | (laserPresent[119]))),  /* 119 */
        ((~(splitterVector[118])) & ((|({(splitterHit[117]),  /* 1 */
        (splitterHit[119])  /* 0 */
        })) | (laserPresent[118]))),  /* 118 */
        ((~(splitterVector[117])) & ((|({(splitterHit[116]),  /* 1 */
        (splitterHit[118])  /* 0 */
        })) | (laserPresent[117]))),  /* 117 */
        ((~(splitterVector[116])) & ((|({(splitterHit[115]),  /* 1 */
        (splitterHit[117])  /* 0 */
        })) | (laserPresent[116]))),  /* 116 */
        ((~(splitterVector[115])) & ((|({(splitterHit[114]),  /* 1 */
        (splitterHit[116])  /* 0 */
        })) | (laserPresent[115]))),  /* 115 */
        ((~(splitterVector[114])) & ((|({(splitterHit[113]),  /* 1 */
        (splitterHit[115])  /* 0 */
        })) | (laserPresent[114]))),  /* 114 */
        ((~(splitterVector[113])) & ((|({(splitterHit[112]),  /* 1 */
        (splitterHit[114])  /* 0 */
        })) | (laserPresent[113]))),  /* 113 */
        ((~(splitterVector[112])) & ((|({(splitterHit[111]),  /* 1 */
        (splitterHit[113])  /* 0 */
        })) | (laserPresent[112]))),  /* 112 */
        ((~(splitterVector[111])) & ((|({(splitterHit[110]),  /* 1 */
        (splitterHit[112])  /* 0 */
        })) | (laserPresent[111]))),  /* 111 */
        ((~(splitterVector[110])) & ((|({(splitterHit[109]),  /* 1 */
        (splitterHit[111])  /* 0 */
        })) | (laserPresent[110]))),  /* 110 */
        ((~(splitterVector[109])) & ((|({(splitterHit[108]),  /* 1 */
        (splitterHit[110])  /* 0 */
        })) | (laserPresent[109]))),  /* 109 */
        ((~(splitterVector[108])) & ((|({(splitterHit[107]),  /* 1 */
        (splitterHit[109])  /* 0 */
        })) | (laserPresent[108]))),  /* 108 */
        ((~(splitterVector[107])) & ((|({(splitterHit[106]),  /* 1 */
        (splitterHit[108])  /* 0 */
        })) | (laserPresent[107]))),  /* 107 */
        ((~(splitterVector[106])) & ((|({(splitterHit[105]),  /* 1 */
        (splitterHit[107])  /* 0 */
        })) | (laserPresent[106]))),  /* 106 */
        ((~(splitterVector[105])) & ((|({(splitterHit[104]),  /* 1 */
        (splitterHit[106])  /* 0 */
        })) | (laserPresent[105]))),  /* 105 */
        ((~(splitterVector[104])) & ((|({(splitterHit[103]),  /* 1 */
        (splitterHit[105])  /* 0 */
        })) | (laserPresent[104]))),  /* 104 */
        ((~(splitterVector[103])) & ((|({(splitterHit[102]),  /* 1 */
        (splitterHit[104])  /* 0 */
        })) | (laserPresent[103]))),  /* 103 */
        ((~(splitterVector[102])) & ((|({(splitterHit[101]),  /* 1 */
        (splitterHit[103])  /* 0 */
        })) | (laserPresent[102]))),  /* 102 */
        ((~(splitterVector[101])) & ((|({(splitterHit[100]),  /* 1 */
        (splitterHit[102])  /* 0 */
        })) | (laserPresent[101]))),  /* 101 */
        ((~(splitterVector[100])) & ((|({(splitterHit[99]),  /* 1 */
        (splitterHit[101])  /* 0 */
        })) | (laserPresent[100]))),  /* 100 */
        ((~(splitterVector[99])) & ((|({(splitterHit[98]),  /* 1 */
        (splitterHit[100])  /* 0 */
        })) | (laserPresent[99]))),  /*  99 */
        ((~(splitterVector[98])) & ((|({(splitterHit[97]),  /* 1 */
        (splitterHit[99])  /* 0 */
        })) | (laserPresent[98]))),  /*  98 */
        ((~(splitterVector[97])) & ((|({(splitterHit[96]),  /* 1 */
        (splitterHit[98])  /* 0 */
        })) | (laserPresent[97]))),  /*  97 */
        ((~(splitterVector[96])) & ((|({(splitterHit[95]),  /* 1 */
        (splitterHit[97])  /* 0 */
        })) | (laserPresent[96]))),  /*  96 */
        ((~(splitterVector[95])) & ((|({(splitterHit[94]),  /* 1 */
        (splitterHit[96])  /* 0 */
        })) | (laserPresent[95]))),  /*  95 */
        ((~(splitterVector[94])) & ((|({(splitterHit[93]),  /* 1 */
        (splitterHit[95])  /* 0 */
        })) | (laserPresent[94]))),  /*  94 */
        ((~(splitterVector[93])) & ((|({(splitterHit[92]),  /* 1 */
        (splitterHit[94])  /* 0 */
        })) | (laserPresent[93]))),  /*  93 */
        ((~(splitterVector[92])) & ((|({(splitterHit[91]),  /* 1 */
        (splitterHit[93])  /* 0 */
        })) | (laserPresent[92]))),  /*  92 */
        ((~(splitterVector[91])) & ((|({(splitterHit[90]),  /* 1 */
        (splitterHit[92])  /* 0 */
        })) | (laserPresent[91]))),  /*  91 */
        ((~(splitterVector[90])) & ((|({(splitterHit[89]),  /* 1 */
        (splitterHit[91])  /* 0 */
        })) | (laserPresent[90]))),  /*  90 */
        ((~(splitterVector[89])) & ((|({(splitterHit[88]),  /* 1 */
        (splitterHit[90])  /* 0 */
        })) | (laserPresent[89]))),  /*  89 */
        ((~(splitterVector[88])) & ((|({(splitterHit[87]),  /* 1 */
        (splitterHit[89])  /* 0 */
        })) | (laserPresent[88]))),  /*  88 */
        ((~(splitterVector[87])) & ((|({(splitterHit[86]),  /* 1 */
        (splitterHit[88])  /* 0 */
        })) | (laserPresent[87]))),  /*  87 */
        ((~(splitterVector[86])) & ((|({(splitterHit[85]),  /* 1 */
        (splitterHit[87])  /* 0 */
        })) | (laserPresent[86]))),  /*  86 */
        ((~(splitterVector[85])) & ((|({(splitterHit[84]),  /* 1 */
        (splitterHit[86])  /* 0 */
        })) | (laserPresent[85]))),  /*  85 */
        ((~(splitterVector[84])) & ((|({(splitterHit[83]),  /* 1 */
        (splitterHit[85])  /* 0 */
        })) | (laserPresent[84]))),  /*  84 */
        ((~(splitterVector[83])) & ((|({(splitterHit[82]),  /* 1 */
        (splitterHit[84])  /* 0 */
        })) | (laserPresent[83]))),  /*  83 */
        ((~(splitterVector[82])) & ((|({(splitterHit[81]),  /* 1 */
        (splitterHit[83])  /* 0 */
        })) | (laserPresent[82]))),  /*  82 */
        ((~(splitterVector[81])) & ((|({(splitterHit[80]),  /* 1 */
        (splitterHit[82])  /* 0 */
        })) | (laserPresent[81]))),  /*  81 */
        ((~(splitterVector[80])) & ((|({(splitterHit[79]),  /* 1 */
        (splitterHit[81])  /* 0 */
        })) | (laserPresent[80]))),  /*  80 */
        ((~(splitterVector[79])) & ((|({(splitterHit[78]),  /* 1 */
        (splitterHit[80])  /* 0 */
        })) | (laserPresent[79]))),  /*  79 */
        ((~(splitterVector[78])) & ((|({(splitterHit[77]),  /* 1 */
        (splitterHit[79])  /* 0 */
        })) | (laserPresent[78]))),  /*  78 */
        ((~(splitterVector[77])) & ((|({(splitterHit[76]),  /* 1 */
        (splitterHit[78])  /* 0 */
        })) | (laserPresent[77]))),  /*  77 */
        ((~(splitterVector[76])) & ((|({(splitterHit[75]),  /* 1 */
        (splitterHit[77])  /* 0 */
        })) | (laserPresent[76]))),  /*  76 */
        ((~(splitterVector[75])) & ((|({(splitterHit[74]),  /* 1 */
        (splitterHit[76])  /* 0 */
        })) | (laserPresent[75]))),  /*  75 */
        ((~(splitterVector[74])) & ((|({(splitterHit[73]),  /* 1 */
        (splitterHit[75])  /* 0 */
        })) | (laserPresent[74]))),  /*  74 */
        ((~(splitterVector[73])) & ((|({(splitterHit[72]),  /* 1 */
        (splitterHit[74])  /* 0 */
        })) | (laserPresent[73]))),  /*  73 */
        ((~(splitterVector[72])) & ((|({(splitterHit[71]),  /* 1 */
        (splitterHit[73])  /* 0 */
        })) | (laserPresent[72]))),  /*  72 */
        ((~(splitterVector[71])) & ((|({(splitterHit[70]),  /* 1 */
        (splitterHit[72])  /* 0 */
        })) | (laserPresent[71]))),  /*  71 */
        ((~(splitterVector[70])) & ((|({(splitterHit[69]),  /* 1 */
        (splitterHit[71])  /* 0 */
        })) | (laserPresent[70]))),  /*  70 */
        ((~(splitterVector[69])) & ((|({(splitterHit[68]),  /* 1 */
        (splitterHit[70])  /* 0 */
        })) | (laserPresent[69]))),  /*  69 */
        ((~(splitterVector[68])) & ((|({(splitterHit[67]),  /* 1 */
        (splitterHit[69])  /* 0 */
        })) | (laserPresent[68]))),  /*  68 */
        ((~(splitterVector[67])) & ((|({(splitterHit[66]),  /* 1 */
        (splitterHit[68])  /* 0 */
        })) | (laserPresent[67]))),  /*  67 */
        ((~(splitterVector[66])) & ((|({(splitterHit[65]),  /* 1 */
        (splitterHit[67])  /* 0 */
        })) | (laserPresent[66]))),  /*  66 */
        ((~(splitterVector[65])) & ((|({(splitterHit[64]),  /* 1 */
        (splitterHit[66])  /* 0 */
        })) | (laserPresent[65]))),  /*  65 */
        ((~(splitterVector[64])) & ((|({(splitterHit[63]),  /* 1 */
        (splitterHit[65])  /* 0 */
        })) | (laserPresent[64]))),  /*  64 */
        ((~(splitterVector[63])) & ((|({(splitterHit[62]),  /* 1 */
        (splitterHit[64])  /* 0 */
        })) | (laserPresent[63]))),  /*  63 */
        ((~(splitterVector[62])) & ((|({(splitterHit[61]),  /* 1 */
        (splitterHit[63])  /* 0 */
        })) | (laserPresent[62]))),  /*  62 */
        ((~(splitterVector[61])) & ((|({(splitterHit[60]),  /* 1 */
        (splitterHit[62])  /* 0 */
        })) | (laserPresent[61]))),  /*  61 */
        ((~(splitterVector[60])) & ((|({(splitterHit[59]),  /* 1 */
        (splitterHit[61])  /* 0 */
        })) | (laserPresent[60]))),  /*  60 */
        ((~(splitterVector[59])) & ((|({(splitterHit[58]),  /* 1 */
        (splitterHit[60])  /* 0 */
        })) | (laserPresent[59]))),  /*  59 */
        ((~(splitterVector[58])) & ((|({(splitterHit[57]),  /* 1 */
        (splitterHit[59])  /* 0 */
        })) | (laserPresent[58]))),  /*  58 */
        ((~(splitterVector[57])) & ((|({(splitterHit[56]),  /* 1 */
        (splitterHit[58])  /* 0 */
        })) | (laserPresent[57]))),  /*  57 */
        ((~(splitterVector[56])) & ((|({(splitterHit[55]),  /* 1 */
        (splitterHit[57])  /* 0 */
        })) | (laserPresent[56]))),  /*  56 */
        ((~(splitterVector[55])) & ((|({(splitterHit[54]),  /* 1 */
        (splitterHit[56])  /* 0 */
        })) | (laserPresent[55]))),  /*  55 */
        ((~(splitterVector[54])) & ((|({(splitterHit[53]),  /* 1 */
        (splitterHit[55])  /* 0 */
        })) | (laserPresent[54]))),  /*  54 */
        ((~(splitterVector[53])) & ((|({(splitterHit[52]),  /* 1 */
        (splitterHit[54])  /* 0 */
        })) | (laserPresent[53]))),  /*  53 */
        ((~(splitterVector[52])) & ((|({(splitterHit[51]),  /* 1 */
        (splitterHit[53])  /* 0 */
        })) | (laserPresent[52]))),  /*  52 */
        ((~(splitterVector[51])) & ((|({(splitterHit[50]),  /* 1 */
        (splitterHit[52])  /* 0 */
        })) | (laserPresent[51]))),  /*  51 */
        ((~(splitterVector[50])) & ((|({(splitterHit[49]),  /* 1 */
        (splitterHit[51])  /* 0 */
        })) | (laserPresent[50]))),  /*  50 */
        ((~(splitterVector[49])) & ((|({(splitterHit[48]),  /* 1 */
        (splitterHit[50])  /* 0 */
        })) | (laserPresent[49]))),  /*  49 */
        ((~(splitterVector[48])) & ((|({(splitterHit[47]),  /* 1 */
        (splitterHit[49])  /* 0 */
        })) | (laserPresent[48]))),  /*  48 */
        ((~(splitterVector[47])) & ((|({(splitterHit[46]),  /* 1 */
        (splitterHit[48])  /* 0 */
        })) | (laserPresent[47]))),  /*  47 */
        ((~(splitterVector[46])) & ((|({(splitterHit[45]),  /* 1 */
        (splitterHit[47])  /* 0 */
        })) | (laserPresent[46]))),  /*  46 */
        ((~(splitterVector[45])) & ((|({(splitterHit[44]),  /* 1 */
        (splitterHit[46])  /* 0 */
        })) | (laserPresent[45]))),  /*  45 */
        ((~(splitterVector[44])) & ((|({(splitterHit[43]),  /* 1 */
        (splitterHit[45])  /* 0 */
        })) | (laserPresent[44]))),  /*  44 */
        ((~(splitterVector[43])) & ((|({(splitterHit[42]),  /* 1 */
        (splitterHit[44])  /* 0 */
        })) | (laserPresent[43]))),  /*  43 */
        ((~(splitterVector[42])) & ((|({(splitterHit[41]),  /* 1 */
        (splitterHit[43])  /* 0 */
        })) | (laserPresent[42]))),  /*  42 */
        ((~(splitterVector[41])) & ((|({(splitterHit[40]),  /* 1 */
        (splitterHit[42])  /* 0 */
        })) | (laserPresent[41]))),  /*  41 */
        ((~(splitterVector[40])) & ((|({(splitterHit[39]),  /* 1 */
        (splitterHit[41])  /* 0 */
        })) | (laserPresent[40]))),  /*  40 */
        ((~(splitterVector[39])) & ((|({(splitterHit[38]),  /* 1 */
        (splitterHit[40])  /* 0 */
        })) | (laserPresent[39]))),  /*  39 */
        ((~(splitterVector[38])) & ((|({(splitterHit[37]),  /* 1 */
        (splitterHit[39])  /* 0 */
        })) | (laserPresent[38]))),  /*  38 */
        ((~(splitterVector[37])) & ((|({(splitterHit[36]),  /* 1 */
        (splitterHit[38])  /* 0 */
        })) | (laserPresent[37]))),  /*  37 */
        ((~(splitterVector[36])) & ((|({(splitterHit[35]),  /* 1 */
        (splitterHit[37])  /* 0 */
        })) | (laserPresent[36]))),  /*  36 */
        ((~(splitterVector[35])) & ((|({(splitterHit[34]),  /* 1 */
        (splitterHit[36])  /* 0 */
        })) | (laserPresent[35]))),  /*  35 */
        ((~(splitterVector[34])) & ((|({(splitterHit[33]),  /* 1 */
        (splitterHit[35])  /* 0 */
        })) | (laserPresent[34]))),  /*  34 */
        ((~(splitterVector[33])) & ((|({(splitterHit[32]),  /* 1 */
        (splitterHit[34])  /* 0 */
        })) | (laserPresent[33]))),  /*  33 */
        ((~(splitterVector[32])) & ((|({(splitterHit[31]),  /* 1 */
        (splitterHit[33])  /* 0 */
        })) | (laserPresent[32]))),  /*  32 */
        ((~(splitterVector[31])) & ((|({(splitterHit[30]),  /* 1 */
        (splitterHit[32])  /* 0 */
        })) | (laserPresent[31]))),  /*  31 */
        ((~(splitterVector[30])) & ((|({(splitterHit[29]),  /* 1 */
        (splitterHit[31])  /* 0 */
        })) | (laserPresent[30]))),  /*  30 */
        ((~(splitterVector[29])) & ((|({(splitterHit[28]),  /* 1 */
        (splitterHit[30])  /* 0 */
        })) | (laserPresent[29]))),  /*  29 */
        ((~(splitterVector[28])) & ((|({(splitterHit[27]),  /* 1 */
        (splitterHit[29])  /* 0 */
        })) | (laserPresent[28]))),  /*  28 */
        ((~(splitterVector[27])) & ((|({(splitterHit[26]),  /* 1 */
        (splitterHit[28])  /* 0 */
        })) | (laserPresent[27]))),  /*  27 */
        ((~(splitterVector[26])) & ((|({(splitterHit[25]),  /* 1 */
        (splitterHit[27])  /* 0 */
        })) | (laserPresent[26]))),  /*  26 */
        ((~(splitterVector[25])) & ((|({(splitterHit[24]),  /* 1 */
        (splitterHit[26])  /* 0 */
        })) | (laserPresent[25]))),  /*  25 */
        ((~(splitterVector[24])) & ((|({(splitterHit[23]),  /* 1 */
        (splitterHit[25])  /* 0 */
        })) | (laserPresent[24]))),  /*  24 */
        ((~(splitterVector[23])) & ((|({(splitterHit[22]),  /* 1 */
        (splitterHit[24])  /* 0 */
        })) | (laserPresent[23]))),  /*  23 */
        ((~(splitterVector[22])) & ((|({(splitterHit[21]),  /* 1 */
        (splitterHit[23])  /* 0 */
        })) | (laserPresent[22]))),  /*  22 */
        ((~(splitterVector[21])) & ((|({(splitterHit[20]),  /* 1 */
        (splitterHit[22])  /* 0 */
        })) | (laserPresent[21]))),  /*  21 */
        ((~(splitterVector[20])) & ((|({(splitterHit[19]),  /* 1 */
        (splitterHit[21])  /* 0 */
        })) | (laserPresent[20]))),  /*  20 */
        ((~(splitterVector[19])) & ((|({(splitterHit[18]),  /* 1 */
        (splitterHit[20])  /* 0 */
        })) | (laserPresent[19]))),  /*  19 */
        ((~(splitterVector[18])) & ((|({(splitterHit[17]),  /* 1 */
        (splitterHit[19])  /* 0 */
        })) | (laserPresent[18]))),  /*  18 */
        ((~(splitterVector[17])) & ((|({(splitterHit[16]),  /* 1 */
        (splitterHit[18])  /* 0 */
        })) | (laserPresent[17]))),  /*  17 */
        ((~(splitterVector[16])) & ((|({(splitterHit[15]),  /* 1 */
        (splitterHit[17])  /* 0 */
        })) | (laserPresent[16]))),  /*  16 */
        ((~(splitterVector[15])) & ((|({(splitterHit[14]),  /* 1 */
        (splitterHit[16])  /* 0 */
        })) | (laserPresent[15]))),  /*  15 */
        ((~(splitterVector[14])) & ((|({(splitterHit[13]),  /* 1 */
        (splitterHit[15])  /* 0 */
        })) | (laserPresent[14]))),  /*  14 */
        ((~(splitterVector[13])) & ((|({(splitterHit[12]),  /* 1 */
        (splitterHit[14])  /* 0 */
        })) | (laserPresent[13]))),  /*  13 */
        ((~(splitterVector[12])) & ((|({(splitterHit[11]),  /* 1 */
        (splitterHit[13])  /* 0 */
        })) | (laserPresent[12]))),  /*  12 */
        ((~(splitterVector[11])) & ((|({(splitterHit[10]),  /* 1 */
        (splitterHit[12])  /* 0 */
        })) | (laserPresent[11]))),  /*  11 */
        ((~(splitterVector[10])) & ((|({(splitterHit[9]),  /* 1 */
        (splitterHit[11])  /* 0 */
        })) | (laserPresent[10]))),  /*  10 */
        ((~(splitterVector[9])) & ((|({(splitterHit[8]),  /* 1 */
        (splitterHit[10])  /* 0 */
        })) | (laserPresent[9]))),  /*   9 */
        ((~(splitterVector[8])) & ((|({(splitterHit[7]),  /* 1 */
        (splitterHit[9])  /* 0 */
        })) | (laserPresent[8]))),  /*   8 */
        ((~(splitterVector[7])) & ((|({(splitterHit[6]),  /* 1 */
        (splitterHit[8])  /* 0 */
        })) | (laserPresent[7]))),  /*   7 */
        ((~(splitterVector[6])) & ((|({(splitterHit[5]),  /* 1 */
        (splitterHit[7])  /* 0 */
        })) | (laserPresent[6]))),  /*   6 */
        ((~(splitterVector[5])) & ((|({(splitterHit[4]),  /* 1 */
        (splitterHit[6])  /* 0 */
        })) | (laserPresent[5]))),  /*   5 */
        ((~(splitterVector[4])) & ((|({(splitterHit[3]),  /* 1 */
        (splitterHit[5])  /* 0 */
        })) | (laserPresent[4]))),  /*   4 */
        ((~(splitterVector[3])) & ((|({(splitterHit[2]),  /* 1 */
        (splitterHit[4])  /* 0 */
        })) | (laserPresent[3]))),  /*   3 */
        ((~(splitterVector[2])) & ((|({(splitterHit[1]),  /* 1 */
        (splitterHit[3])  /* 0 */
        })) | (laserPresent[2]))),  /*   2 */
        ((~(splitterVector[1])) & ((|({(splitterHit[0]),  /* 1 */
        (splitterHit[2])  /* 0 */
        })) | (laserPresent[1]))),  /*   1 */
        ((~(splitterVector[0])) & ((|(splitterHit[1])) | (laserPresent[0])))  /*   0 */
      });  // flipflop
  assign splitterHit = splitterVector & laserPresent;  // and__0
endmodule : Day07p1
